### ISSUE TITLE
Broken Icon for Test Suites

### ISSUE THREAD

**Issue by gibbok** [poplindata/chrome-snowplow-inspector#71] opened 2023-10-02 06:14 UTC
The icon next to the "Test Suites" is broken, (it seems the related character is missing in the loaded font):

Please have a look here:

<img width="2515" alt="Screenshot 2023-10-02 at 8 09 14 AM" src="https://github.com/poplindata/chrome-snowplow-inspector/assets/17195702/4e7c818c-da87-419d-8408-e466ce559047">

Icon should be visible correctly similarly to:

<img width="2515" alt="Screenshot 2023-10-02 at 8 10 35 AM" src="https://github.com/poplindata/chrome-snowplow-inspector/assets/17195702/ca66b3a6-ac4b-4a31-bd0c-4a182a8b0e25">

**Comment by jethron** [comment] 2023-10-03 02:25
Thanks a lot for the report @gibbok! Hopefully fixed by e33d3c75c32fa1392e9375cb2295f80e5c36dcc7 - I presume this is on macOS? @miike would you be able to validate when you have a moment (it works fine on Linux, should be a little pencil icon)?

Also, welcome aboard! :wink:

**Comment by gibbok** [comment] 2023-10-03 08:02
Thanks for your message. Yes it found it on macOS 14.0,

**Comment by jethron** [comment] 2023-11-07 01:50
Ended up switching to a different emoji that has better support (:gear:). For whatever reason macOS doesn't fall back to the full-color emoji and doesn't want to use the symbollic version (which I think comes from the Webdings font?) for the pencil icon that was intended.

Thanks for the report @gibbok!

**Closed by jethron** 2023-11-07 01:50 UTC
