### ISSUE TITLE
Firefox version of latest builds

### ISSUE THREAD

**Issue by paulboocock** [poplindata/chrome-snowplow-inspector#58] opened 2022-08-15 16:06 UTC
In 2019, there were Firefox builds published to Github Releases.

Would it be possible to bring these back for the latest versions of the extension?

**Comment by jethron** [comment] 2022-08-16 06:52
Not super easy to automate yet as Firefox still only supports Manifest v2. A release involves manually downgrading that file in order to sign the release and generate an .XPI that's actually installable.

I've done this for [v0.2.22](https://github.com/poplindata/chrome-snowplow-inspector/releases/tag/v0.2.22) and will do it manually for future releases until Firefox has broader v3 support. Will leave open until this is a simpler process.

It's mostly untested in Firefox these days, please let us know if you encounter any bugs @paulboocock!

**Comment by paulboocock** [comment] 2022-08-16 13:39
I'll give it a shot, thanks @jethron! I'll pass it on to the person who asked me for this too :-D

**Comment by hallvardlid** [comment] 2022-09-13 09:29
> It's mostly untested in Firefox these days, please let us know if you encounter any bugs

The igluCentral repo does not resolve i firefox - not sure what the issue is. Havent found a manifest-URI anywhere - so havent testing adding that to the config. When installing in Chrome i get all the schemas from central automatic(after allowing the plugin to talk to that url). I have allowed the plugin to "Access your data for all websites"

I have a schemaregistry of the "iglu Server/Mini Api"-kind as well - and it works fine.

**Comment by jethron** [comment] 2022-09-14 04:55
Thanks for the report @hallvardlid!

Looks like this is a longstanding API incompatibility between Firefox and Chrome where we can't request permissions from DevTools panels apparently: https://bugzilla.mozilla.org/show_bug.cgi?id=1453343

It seems to be a case of Chrome not actually following their own documented behaviour (quoted in that issue), whereas Firefox does. I've tried the suggested workaround (message passing to a background script to request the permissions), but as you can only request permissions within a user action (e.g. a click handler), this too fails. So it appears it's not actually possible to request user permissions easily from a DevTools panel in Firefox at the moment.

The Iglu Server/Mini registry will be working because it usually supports CORS, which means we don't need the explicit permission to make the network request, the browser just allows it. As most static registries (including Iglu Central) did not historically support that, we required the explicit permission. Looks like that has changed and these days Iglu Central _does_ support CORS directly, so I've adjusted the logic to attempt the request, and only request the permission if that fails due to CORS. So this will be fixed in the next version, but only if CORS is supported. Other static registries without CORS support will continue to fail in Firefox, unfortunately.

> Havent found a manifest-URI anywhere - so havent testing adding that to the config.
Without a manifest URI it defaults to trying `/schemas`, which [Iglu Central does support](http://iglucentral.com/schemas), so that shouldn't matter much.

There aren't many other changes awaiting release at the moment, but if there's nothing else by the end of the week I'll cut a new version just for this.

**Comment by jethron** [comment] 2023-06-14 02:57
Manifest v3 seems to work for Firefox now, will include those builds in future releases, closing this.

**Closed** 2023-06-14 02:57 UTC
Labels: enhancement
